### PR TITLE
Added alternate `EndBytes' function; includes corresponding unit-test.

### PR DESCRIPTION
**Pull request by jaytaylor**
This PR makes it possible to still easily get at the body as bytes.  This makes it possible to avoid incurring the undesirable overhead of doing a double copy from bytes -> string -> bytes when dealing with large response bodies.

### CODE REVIEW

**Comment by alaingilbert** [comment]
Hi,
I think the following solution better suit your needs:
https://github.com/parnurzeal/gorequest/pull/36

Basically, we just ensure that "resp.Body" can be reused (just like a normal http.Response)

**Comment by jaytaylor** [comment]
Hi @alaingilbert, thanks for reviewing this PR.

Being able to reuse the r.Body is great for this package!

In the use-case of immediately deserializing the response.Body into JSON, user's need a straightforward way to access the body as a byte slice.  The simplest way to do this is to provide a way to shuttle the bytes straight back to them, as per this PR.

Forcing them to re-read the body introduces unnecessary overhead in unused allocations and is also less friendly from an API perspective.

**Comment by parnurzeal** [comment]
Thanks for this and sorry for really slow response to this PR.

This is actually very very nice one with good testing. 
I will merge to master soon and put you to contribution list.

**Comment by jaytaylor** [comment]
Fantastic, thank you for merging this!

**Pull request merged**
