### PR TITLE
"Clone" the SuperAgent for reuse

### PR DESCRIPTION
**Pull request by fromkeith**
The aim of this is to allow a base gorequest to be re-used throughout someone's code base.

Ideally, gorequest itself would be concurrent safe, but I think that would require much larger changes (and possibly API changes). This takes the approach of _Cloning_ the base gorequest, so it can be safely used by multiple routines at the same time.

In my scenario I run a web server. I want to be able to easily re-use a single gorequest base, that gets configured at startup (Eg. timeout, transport, auth, etc...). Adding the Clone method lets me do this safely without running into concurrency issues. 

While refactoring a bit a few other changes had to be made:
1. The "Timeout" function points to the base gorequest. It also looks like it may have been written after http.Client.Timeout existed. So I switched it to that. Let me know if my assumption there is wrong.
2. Try to "safely" manage any changes to http.Client & http.Transport. Ideally the user should not be allowed to edit the Client or Transport after calling Clone. However, that would break the API. So instead, I do a "best effort" clone of the Client and Transport so a clone cannot affect the base.

An example is provided in the readme, with this code example:
```go
baseRequest := gorequest.New()
// apply anything you want to these settings. Eg:
baseRequest.Timeout(10 * time.Millisecond).
  BasicAuth("user", "password")

// then reuse the base request elsewhere, cloning before modifying or using it.
resp, body, errs := baseRequest.Clone().Get("http://exmaple.com/").End()
```

Should fix, or provide a workaround for
#147 - Concurrent write access to a map. Clone makes new Header & Query maps. Should solve this issue.
#125 - Clone allows the underlying Client and transport to be re-used.
#73 - Calling Clone on the base allows for re-use
#27 - Should fix most of the concurrency issues if Clone is used.

Let me know what you think!

### CODE REVIEW

**Comment by parnurzeal** [comment]
Thank you for this big effort!!! 
Please hang on. I will review the code soon within a couple days.

**Comment by lenfree** [comment]
Hi, any update on this? 😄

**Comment by jryd** [comment]
Can we please get this merged, it would incredibly useful!

**Comment by fromkeith** [comment]
I resolved the merge conflicts.

**Comment by h7kanna** [comment]
Hi, 
Why is this not being merged?
Thanks,

**Comment by junjzh** [comment]
ping

**Comment by lalit-verma** [comment]
@parnurzeal @QuentinPerez Guys Any update on this one ?
Do you guys plan on merging this ?

**Comment by zbw0046** [comment]
ping

**Comment by zhaohansprt** [comment]
what is going on

**Comment by zhaohansprt** [comment]
i use common pool for reuse  check [this ](https://github.com/jolestar/go-commons-pool)

**Comment by liunian1004** [comment]
is that means i can use the `keep alive` to fix desc leak issue like:

```go
r := gorequest.New()
r.Transport.DisableKeepAlives = false

// when send request use Clone()
r.Clone().Post()....
```

**Pull request merged**
