### PR TITLE
Add http2curl

### PR DESCRIPTION
**Pull request by QuentinPerez**
Hello,

I added a method to display a CURL command line.
```console
$> cat curl.go
package main

import "github.com/parnurzeal/gorequest"

func main() {
	gorequest.New().Get("https://www.google.com").SetCurlCommand(true).End()
	gorequest.New().Post("https://www.google.com").SetCurlCommand(true).Send("{\"foo\": \"bar\"}").End()
}
$> go run curl.go
[curl] 2015/10/16 12:22:03 CURL command line: curl -X GET https://www.google.com
[curl] 2015/10/16 12:22:03 CURL command line: curl -X POST -d "{\"foo\":\"bar\"}" -H "Content-Type: application/json" https://www.google.com
```

### CODE REVIEW

**Comment by parnurzeal** [comment]
Hi QuentinPerez,

Thanks for the pull request. Can you have a look why the checks failed?

**Comment by QuentinPerez** [comment]
Hi @parnurzeal 

The PR failed, because I have imported `github.com/moul/http2curl`.
I can make a dedicated `vendor` directory with this dependency.

**Comment by QuentinPerez** [comment]
ping @parnurzeal

**Comment by parnurzeal** [comment]
Sorry for late on this. 
I was trying to be considerate on adding another dependency package beside standard ones.

Anyway, merging it now. It is very very nice feature to have. I really like it.

Btw, I am not sure about this but wanna ask whether you want to be co-maintainer on this gorequest?

**Comment by QuentinPerez** [comment]
Hello, 

I will be delighted to work with you as a co-maintainer on this repository.

**Comment by parnurzeal** [comment]
Very glad to hear this! Could you send me an email to [ parnurzeal at
gmail.com ]?
I would like to send some brief introduction for this repo back to you by
email.

**Pull request merged**
