### PR TITLE
Use number when unmarshal json

### PR DESCRIPTION
**Pull request by killix**
Allow the support of json number.
Example:
```
{
"Name":"Marc",
"id":12423434
}
```

### CODE REVIEW

**Comment by parnurzeal** [comment]
Testing & a bit improvement has been implemented in different branch.
This feature will be included in the next version release. 
I will put your name in contributor section as well as in release note. 

Thanks!

**Comment by killix** [comment]
oupps sorry for the time of response and thanks for update test for me ;)

**Comment by panamafrancis** [comment]
it would be amazing if you could merge develop with master or at least this fix into master.

gracias!

**Comment by parnurzeal** [comment]
I am planning to do it within today!  Thanks for pinging :)

**Comment by parnurzeal** [comment]
It's merged to Master.

**Pull request closed without merging**
