### PR TITLE
add context support

### PR DESCRIPTION
**Pull request by xiaoniaojun**
Hi, I'm a newbie gopher and I like your gorequest  lib so much, now I'm using it in production env, tks for your work!
recently, when I write code with gorequest, I found it wasn't support the Context type, which provided by go itself and greatly benefit http connection control.   net.http support context, and I found a sample way to add this support to gorequest. I hope you can check my code, and provide some suggestion, thks very much!

### CODE REVIEW

**Review by sensugaz — APPROVED** [review]

**Review by hilaily — APPROVED** [review]
Please merge it, context is important for us.

**Comment by duguying** [comment]
@parnurzeal can you merge it into master and give it a tag?

**Comment by parnurzeal** [comment]
Done. Tag is `v0.3.0`.

**Comment by duguying** [comment]
thank you

**Pull request merged**
